return {
-- 	"VonHeikemen/fine-cmdline.nvim",
-- 	dependencies = "MunifTanjim/nui.nvim",
-- 	lazy = false,
-- 	opts = {
-- 		cmdline = {
-- 			enable_keymaps = true,
-- 			smart_history = true,
-- 			prompt = ': '
-- 		},
-- 		popup = {
-- 			position = {
-- 				row = '90%',
-- 				col = '50%',
-- 			},
-- 			size = {
-- 				width = '60%',
-- 			},
-- 			border = {
-- 				style = 'rounded',
-- 			},
-- 			win_options = {
-- 				winhighlight = 'Normal:Normal,FloatBorder:FloatBorder',
-- 			},
-- 		},
-- 	},
--
-- 	init = function(imap, feedkeys)
-- 		vim.api.nvim_set_keymap('n', ':', '<cmd>FineCmdline<CR>', {noremap = true})
-- 		vim.opt.cmdheight = 0
-- 	end
}
